# Reference: https://cloud.google.com/cloud-build/docs/build-config

steps:
  - name: gcr.io/$PROJECT_ID/packer
    args:
      - build
      - -timestamp-ui
      - -var=graftorio_addon=$_GRAFTORIO_ADDON
      - -var=image_family=$_IMAGE_FAMILY
      - -var=image_name=$_IMAGE_NAME
      - -var=image_zone=$_IMAGE_ZONE
      - -var=project_id=$PROJECT_ID
      - factorio-server.pkr.hcl

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: gcloud
    args:
      - compute
      - instance-templates
      - create
      - --boot-disk-device-name=${_IMAGE_FAMILY}-1
      - --boot-disk-size=20GB
      - --boot-disk-type=pd-standard
      - --description=https://github.com/jlucktay/factorio-server-kit
      - --image=$_IMAGE_NAME
      - --machine-type=n2-standard-2
      - --maintenance-policy=TERMINATE
      - --metadata-from-file=startup-script=startup.sh,shutdown-script=shutdown.sh
      - --network-tier=PREMIUM
      - --network=projects/${PROJECT_ID}/global/networks/default
      - --no-restart-on-failure
      # "A best practice is to set the full cloud-platform access scope on the instance, then securely limit the
      # service account's API access with Cloud IAM roles."
      # Ref: https://cloud.google.com/compute/docs/access/service-accounts#accesscopesiam
      - --scopes=https://www.googleapis.com/auth/cloud-platform
      - --service-account=factorio-server@${PROJECT_ID}.iam.gserviceaccount.com
      - --tags=factorio,grafana,ssh
      - $_IMAGE_NAME
