# Reference: https://cloud.google.com/cloud-build/docs/build-config

steps:
  - name: gcr.io/cloud-builders/wget
    args:
      - --progress=dot:giga
      - https://releases.hashicorp.com/packer/${_PACKER_VERSION}/packer_${_PACKER_VERSION}_linux_amd64.zip

  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --build-arg=PACKER_VERSION=${_PACKER_VERSION}
      - --build-arg=PACKER_VERSION_SHA256SUM=${_PACKER_VERSION_SHA256SUM}
      - --cache=true
      - --destination=gcr.io/$PROJECT_ID/packer
      - --destination=gcr.io/$PROJECT_ID/packer:${_PACKER_VERSION}

  # Version check
  - name: gcr.io/$PROJECT_ID/packer
    args:
      - version
